--
-- PostgreSQL database dump
--

\restrict acHjbRzMnPeVRcLyt2fBoz8GNyTbJbxDhlznDpNrsfNatHuyyjqbtIfmBPpe42W

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.3 (Debian 18.3-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: account_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.account_status AS ENUM (
    'active',
    'inactive',
    'banned'
);


--
-- Name: app_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.app_status AS ENUM (
    'active',
    'inactive'
);


--
-- Name: billing_mode; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.billing_mode AS ENUM (
    'indefinite',
    'monthly',
    'quarterly',
    'semi_annually',
    'annually',
    'long_term'
);


--
-- Name: plan_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.plan_status AS ENUM (
    'active',
    'inactive'
);


--
-- Name: subscription_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.subscription_status AS ENUM (
    'active',
    'canceled',
    'past_due',
    'paused'
);


--
-- Name: token_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.token_type AS ENUM (
    'access_token',
    'email_otp',
    'password_otp'
);


--
-- Name: transaction_origin; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.transaction_origin AS ENUM (
    'plan',
    'usage'
);


--
-- Name: transaction_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.transaction_status AS ENUM (
    'draft',
    'ready',
    'billed',
    'paid',
    'completed',
    'canceled',
    'past_due'
);


--
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
                BEGIN
                    NEW.updated_at = NOW();
                    RETURN NEW;
                END;
                $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_user_permissions (
    account_user_id bigint NOT NULL,
    permission_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: account_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_users (
    id bigint NOT NULL,
    user_name character varying NOT NULL,
    role character varying NOT NULL,
    account_id bigint NOT NULL,
    password character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: account_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    alias character varying NOT NULL,
    name character varying NOT NULL,
    email character varying NOT NULL,
    status public.account_status DEFAULT 'active'::public.account_status NOT NULL,
    role character varying,
    password character varying NOT NULL,
    payment_provider character varying,
    payment_provider_id character varying,
    email_verified_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.apps (
    id bigint NOT NULL,
    name character varying NOT NULL,
    description text NOT NULL,
    client_id text,
    client_secret text,
    signing_secret text,
    account_id bigint NOT NULL,
    keys_generated_at timestamp with time zone,
    status public.app_status DEFAULT 'active'::public.app_status NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: apps_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.apps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_tokens (
    id bigint NOT NULL,
    account_id bigint NOT NULL,
    account_user_id bigint,
    token character varying NOT NULL,
    token_type public.token_type NOT NULL,
    meta json,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: auth_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    id integer NOT NULL,
    name character varying NOT NULL,
    description character varying,
    is_system boolean DEFAULT false NOT NULL,
    is_account_accessible boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_prices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_prices (
    id integer NOT NULL,
    provider_id character varying,
    provider character varying,
    title character varying NOT NULL,
    plan_slug character varying NOT NULL,
    billing_mode public.billing_mode NOT NULL,
    cost_in_cents bigint NOT NULL,
    currency character varying DEFAULT 'USD'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: plan_prices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plan_prices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_prices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plans (
    slug character varying NOT NULL,
    provider_id character varying,
    provider character varying,
    title character varying NOT NULL,
    description character varying NOT NULL,
    connection_rate_limit_per_second bigint NOT NULL,
    connection_message_rate_limit_per_second bigint NOT NULL,
    message_rate_limit_per_second bigint NOT NULL,
    message_rate_limit_per_hour bigint,
    message_rate_limit_per_month bigint,
    concurrent_connection_limit bigint NOT NULL,
    concurrent_channel_limit bigint NOT NULL,
    features json NOT NULL,
    status public.plan_status NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT positive_concurrent_channel_limit CHECK ((concurrent_channel_limit > 0)),
    CONSTRAINT positive_concurrent_connection_limit CHECK ((concurrent_connection_limit > 0)),
    CONSTRAINT positive_connection_message_rate_limit_per_second CHECK ((connection_message_rate_limit_per_second > 0)),
    CONSTRAINT positive_connection_rate_limit_per_second CHECK ((connection_rate_limit_per_second > 0)),
    CONSTRAINT positive_message_rate_limit_per_hour CHECK ((message_rate_limit_per_hour > 0)),
    CONSTRAINT positive_message_rate_limit_per_month CHECK ((message_rate_limit_per_month > 0)),
    CONSTRAINT positive_message_rate_limit_per_second CHECK ((message_rate_limit_per_second > 0))
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    role_slug character varying NOT NULL,
    permission_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    slug character varying NOT NULL,
    name character varying NOT NULL,
    description character varying,
    is_system boolean DEFAULT false NOT NULL,
    is_account_accessible boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: seaql_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seaql_migrations (
    version character varying NOT NULL,
    applied_at bigint NOT NULL
);


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscriptions (
    id bigint NOT NULL,
    plan_price_id integer NOT NULL,
    account_id bigint NOT NULL,
    provider_id character varying NOT NULL,
    provider character varying DEFAULT 'paddle'::character varying NOT NULL,
    status public.subscription_status DEFAULT 'active'::public.subscription_status NOT NULL,
    defaulting_payment_in_cents bigint DEFAULT 0 NOT NULL,
    last_usage_transaction_id bigint,
    starts_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ends_at timestamp with time zone,
    status_updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    usage_period_starts_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_usage_transaction_attempted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    account_id bigint NOT NULL,
    provider_id character varying,
    provider character varying DEFAULT 'paddle'::character varying NOT NULL,
    description character varying NOT NULL,
    items json NOT NULL,
    status public.transaction_status DEFAULT 'draft'::public.transaction_status NOT NULL,
    total_in_cents bigint NOT NULL,
    currency character varying DEFAULT 'USD'::character varying NOT NULL,
    origin public.transaction_origin NOT NULL,
    billed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usage_plan_prices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usage_plan_prices (
    slug character varying NOT NULL,
    provider character varying,
    name character varying NOT NULL,
    unit character varying NOT NULL,
    provider_id character varying,
    provider_price_id character varying,
    cost_in_cents bigint NOT NULL,
    currency character varying DEFAULT 'USD'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Data for Name: account_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.account_user_permissions (account_user_id, permission_id, created_at) FROM stdin;
\.


--
-- Data for Name: account_users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.account_users (id, user_name, role, account_id, password, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.accounts (id, alias, name, email, status, role, password, payment_provider, payment_provider_id, email_verified_at, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: apps; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.apps (id, name, description, client_id, client_secret, signing_secret, account_id, keys_generated_at, status, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: auth_tokens; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_tokens (id, account_id, account_user_id, token, token_type, meta, expires_at, created_at) FROM stdin;
\.


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.permissions (id, name, description, is_system, is_account_accessible, created_at) FROM stdin;
1	account:*	Wildcard: all account permissions	t	t	2026-06-22 13:02:06.152526+00
2	account:read	View account profile and settings	t	t	2026-06-22 13:02:06.152526+00
3	account:update	Update account info (name, email, password)	t	t	2026-06-22 13:02:06.152526+00
4	account:delete	Delete the account	t	t	2026-06-22 13:02:06.152526+00
5	app:*	Wildcard: all app permissions	t	t	2026-06-22 13:02:06.152526+00
6	app:create	Create new apps	t	t	2026-06-22 13:02:06.152526+00
7	app:read	View app list and details	t	t	2026-06-22 13:02:06.152526+00
8	app:update	Update app name, description, and status	t	t	2026-06-22 13:02:06.152526+00
9	app:delete	Delete apps	t	t	2026-06-22 13:02:06.152526+00
10	app:generate_keys	Regenerate client_id, client_secret, and signing_secret	t	t	2026-06-22 13:02:06.152526+00
11	channel:*	Wildcard: all channel permissions	t	t	2026-06-22 13:02:06.152526+00
12	channel:read	View channel list and details	t	t	2026-06-22 13:02:06.152526+00
13	channel:manage	Create, update, and delete channels	t	t	2026-06-22 13:02:06.152526+00
14	subscription:*	Wildcard: all subscription permissions	t	t	2026-06-22 13:02:06.152526+00
15	subscription:read	View current subscription and plan details	t	t	2026-06-22 13:02:06.152526+00
16	subscription:create	Subscribe to a plan	t	t	2026-06-22 13:02:06.152526+00
17	subscription:update	Upgrade or downgrade subscription plan	t	t	2026-06-22 13:02:06.152526+00
18	subscription:cancel	Cancel an active subscription	t	t	2026-06-22 13:02:06.152526+00
19	analytics:*	Wildcard: all analytics permissions	t	t	2026-06-22 13:02:06.152526+00
20	analytics:read	View metrics, dashboards, and usage stats	t	t	2026-06-22 13:02:06.152526+00
21	role:*	Wildcard: all role permissions	t	t	2026-06-22 13:02:06.152526+00
22	role:read	List roles and their permission assignments	t	t	2026-06-22 13:02:06.152526+00
23	role:create	Create custom roles	t	t	2026-06-22 13:02:06.152526+00
24	role:update	Modify role name and description	t	t	2026-06-22 13:02:06.152526+00
25	role:delete	Delete roles	t	t	2026-06-22 13:02:06.152526+00
26	permission:*	Wildcard: all permission permissions	t	t	2026-06-22 13:02:06.152526+00
27	permission:assign	Assign or revoke permissions from a role	t	t	2026-06-22 13:02:06.152526+00
\.


--
-- Data for Name: plan_prices; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.plan_prices (id, provider_id, provider, title, plan_slug, billing_mode, cost_in_cents, currency, created_at, updated_at) FROM stdin;
1	\N	\N	Free	free	indefinite	0	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
2	\N	\N	Standard Monthly	standard	monthly	2000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
3	\N	\N	Standard Quarterly	standard	quarterly	5700	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
4	\N	\N	Standard Semi-Annually	standard	semi_annually	10800	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
5	\N	\N	Standard Annually	standard	annually	20000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
6	\N	\N	Standard Long-Term	standard	long_term	48000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
7	\N	\N	Pro Monthly	pro	monthly	25000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
8	\N	\N	Pro Quarterly	pro	quarterly	71300	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
9	\N	\N	Pro Semi-Annually	pro	semi_annually	135000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
10	\N	\N	Pro Annually	pro	annually	250000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
11	\N	\N	Pro Long-Term	pro	long_term	600000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
12	\N	\N	Prime Monthly	prime	monthly	120000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
13	\N	\N	Prime Quarterly	prime	quarterly	342000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
14	\N	\N	Prime Semi-Annually	prime	semi_annually	648000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
15	\N	\N	Prime Annually	prime	annually	1200000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
16	\N	\N	Prime Long-Term	prime	long_term	2880000	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
\.


--
-- Data for Name: plans; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.plans (slug, provider_id, provider, title, description, connection_rate_limit_per_second, connection_message_rate_limit_per_second, message_rate_limit_per_second, message_rate_limit_per_hour, message_rate_limit_per_month, concurrent_connection_limit, concurrent_channel_limit, features, status, created_at, updated_at) FROM stdin;
free	\N	\N	Free	Get started with Celeris at no cost.	50	50	500	\N	6000000	200	200	[]	active	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
standard	\N	\N	Standard	For growing teams and production workloads.	250	100	2500	\N	\N	10000	10000	[]	active	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
pro	\N	\N	Pro	For high-throughput applications.	500	150	10000	\N	\N	50000	50000	[]	active	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
prime	\N	\N	Prime	For large-scale, enterprise-grade deployments.	1000	250	50000	\N	\N	250000	250000	[]	active	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
\.


--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.role_permissions (role_slug, permission_id, created_at) FROM stdin;
super_admin	1	2026-06-22 13:02:06.152526+00
super_admin	5	2026-06-22 13:02:06.152526+00
super_admin	11	2026-06-22 13:02:06.152526+00
super_admin	14	2026-06-22 13:02:06.152526+00
super_admin	19	2026-06-22 13:02:06.152526+00
super_admin	21	2026-06-22 13:02:06.152526+00
super_admin	26	2026-06-22 13:02:06.152526+00
account_owner	1	2026-06-22 13:02:06.152526+00
account_owner	5	2026-06-22 13:02:06.152526+00
account_owner	11	2026-06-22 13:02:06.152526+00
account_owner	14	2026-06-22 13:02:06.152526+00
account_owner	19	2026-06-22 13:02:06.152526+00
account_owner	22	2026-06-22 13:02:06.152526+00
app_keys_role	1	2026-06-22 13:02:06.152526+00
app_keys_role	5	2026-06-22 13:02:06.152526+00
app_keys_role	11	2026-06-22 13:02:06.152526+00
app_keys_role	14	2026-06-22 13:02:06.152526+00
app_keys_role	19	2026-06-22 13:02:06.152526+00
app_keys_role	22	2026-06-22 13:02:06.152526+00
developer	2	2026-06-22 13:02:06.152526+00
developer	5	2026-06-22 13:02:06.152526+00
developer	11	2026-06-22 13:02:06.152526+00
developer	19	2026-06-22 13:02:06.152526+00
billing_manager	2	2026-06-22 13:02:06.152526+00
billing_manager	14	2026-06-22 13:02:06.152526+00
billing_manager	19	2026-06-22 13:02:06.152526+00
viewer	2	2026-06-22 13:02:06.152526+00
viewer	7	2026-06-22 13:02:06.152526+00
viewer	12	2026-06-22 13:02:06.152526+00
viewer	15	2026-06-22 13:02:06.152526+00
viewer	19	2026-06-22 13:02:06.152526+00
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles (slug, name, description, is_system, is_account_accessible, created_at) FROM stdin;
super_admin	Super Admin	Platform administrator with full access to everything	t	f	2026-06-22 13:02:06.152526+00
account_owner	Account Owner	Owner of an account with full access to their resources	t	f	2026-06-22 13:02:06.152526+00
app_keys_role	App Keys Role	Roles with access to app keys	t	f	2026-06-22 13:02:06.152526+00
developer	Developer	Can create and manage apps, generate keys, and view metrics	t	t	2026-06-22 13:02:06.152526+00
billing_manager	Billing Manager	Can manage subscriptions and billing only	t	t	2026-06-22 13:02:06.152526+00
viewer	Viewer	Read-only access to apps, channels, metrics, and subscriptions	t	t	2026-06-22 13:02:06.152526+00
\.


--
-- Data for Name: seaql_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.seaql_migrations (version, applied_at) FROM stdin;
m20250309_002430_bootstrap_migration	1782133326
m20250310_214625_create_roles_table	1782133326
m20250311_214907_create_permissions_table	1782133326
m20250312_215624_create_role_permissions_table	1782133326
m20250313_115625_seed_roles_and_permissions	1782133326
m20250324_002438_create_accounts_table	1782133326
m20250329_202820_create_app_table	1782133326
m20260505_100606_create_plan_table	1782133326
m20260505_112117_create_plan_prices_table	1782133326
m20260506_201007_create_transactions_table	1782133326
m20260507_115948_create_subscriptions_table	1782133326
m20260512_134021_create_usage_plan_price_table	1782133326
m20260512_160846_seed_plan_and_plan_price	1782133326
m20260518_155202_create_account_user_table	1782133326
m20260518_162838_create_user_permission_table	1782133326
m20260518_162840_create_auth_token_table	1782133326
\.


--
-- Data for Name: subscriptions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.subscriptions (id, plan_price_id, account_id, provider_id, provider, status, defaulting_payment_in_cents, last_usage_transaction_id, starts_at, ends_at, status_updated_at, usage_period_starts_at, last_usage_transaction_attempted_at, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.transactions (id, account_id, provider_id, provider, description, items, status, total_in_cents, currency, origin, billed_at, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: usage_plan_prices; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usage_plan_prices (slug, provider, name, unit, provider_id, provider_price_id, cost_in_cents, currency, created_at, updated_at) FROM stdin;
message	\N	Message	million messages	\N	\N	200	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
connection	\N	Connection Minutes	million connection minutes	\N	\N	100	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
channel	\N	Channel Minutes	million channel minutes	\N	\N	100	USD	2026-06-22 13:02:06.20366+00	2026-06-22 13:02:06.20366+00
\.


--
-- Name: account_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.account_users_id_seq', 1, false);


--
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_id_seq', 1, false);


--
-- Name: apps_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.apps_id_seq', 1, false);


--
-- Name: auth_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_tokens_id_seq', 1, false);


--
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.permissions_id_seq', 27, true);


--
-- Name: plan_prices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.plan_prices_id_seq', 16, true);


--
-- Name: subscriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.subscriptions_id_seq', 1, false);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.transactions_id_seq', 1, false);


--
-- Name: account_user_permissions account_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_user_permissions
    ADD CONSTRAINT account_user_permissions_pkey PRIMARY KEY (account_user_id, permission_id);


--
-- Name: account_users account_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_users
    ADD CONSTRAINT account_users_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_alias_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_alias_key UNIQUE (alias);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: apps apps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.apps
    ADD CONSTRAINT apps_pkey PRIMARY KEY (id);


--
-- Name: auth_tokens auth_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_tokens
    ADD CONSTRAINT auth_tokens_pkey PRIMARY KEY (id);


--
-- Name: auth_tokens auth_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_tokens
    ADD CONSTRAINT auth_tokens_token_key UNIQUE (token);


--
-- Name: permissions permissions_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_name_key UNIQUE (name);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: plan_prices plan_prices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_prices
    ADD CONSTRAINT plan_prices_pkey PRIMARY KEY (id);


--
-- Name: plan_prices plan_prices_provider_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_prices
    ADD CONSTRAINT plan_prices_provider_id_key UNIQUE (provider_id);


--
-- Name: plans plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (slug);


--
-- Name: plans plans_provider_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_provider_id_key UNIQUE (provider_id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_slug, permission_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (slug);


--
-- Name: seaql_migrations seaql_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seaql_migrations
    ADD CONSTRAINT seaql_migrations_pkey PRIMARY KEY (version);


--
-- Name: subscriptions subscriptions_account_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_account_id_key UNIQUE (account_id);


--
-- Name: subscriptions subscriptions_last_usage_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_last_usage_transaction_id_key UNIQUE (last_usage_transaction_id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_provider_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_provider_id_key UNIQUE (provider_id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_provider_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_provider_id_key UNIQUE (provider_id);


--
-- Name: usage_plan_prices usage_plan_prices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usage_plan_prices
    ADD CONSTRAINT usage_plan_prices_pkey PRIMARY KEY (slug);


--
-- Name: account_users_user_name_account_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX account_users_user_name_account_id_idx ON public.account_users USING btree (user_name, account_id);


--
-- Name: idx_plan_price_plan_slug_billing_mode; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_price_plan_slug_billing_mode ON public.plan_prices USING btree (plan_slug, billing_mode);


--
-- Name: account_users update_account_users_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_account_users_updated_at BEFORE UPDATE ON public.account_users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: accounts update_accounts_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_accounts_updated_at BEFORE UPDATE ON public.accounts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: apps update_apps_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_apps_updated_at BEFORE UPDATE ON public.apps FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: plan_prices update_plan_prices_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_plan_prices_updated_at BEFORE UPDATE ON public.plan_prices FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: plans update_plans_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_plans_updated_at BEFORE UPDATE ON public.plans FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: subscriptions update_subscriptions_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_subscriptions_updated_at BEFORE UPDATE ON public.subscriptions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: transactions update_transactions_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER update_transactions_updated_at BEFORE UPDATE ON public.transactions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: account_user_permissions account_user_permissions_account_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_user_permissions
    ADD CONSTRAINT account_user_permissions_account_user_id_fkey FOREIGN KEY (account_user_id) REFERENCES public.account_users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: account_user_permissions account_user_permissions_permission_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_user_permissions
    ADD CONSTRAINT account_user_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: account_users account_users_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_users
    ADD CONSTRAINT account_users_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: account_users account_users_role_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_users
    ADD CONSTRAINT account_users_role_fkey FOREIGN KEY (role) REFERENCES public.roles(slug) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: accounts accounts_role_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_role_fkey FOREIGN KEY (role) REFERENCES public.roles(slug) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: apps apps_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.apps
    ADD CONSTRAINT apps_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: auth_tokens auth_tokens_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_tokens
    ADD CONSTRAINT auth_tokens_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: auth_tokens auth_tokens_account_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_tokens
    ADD CONSTRAINT auth_tokens_account_user_id_fkey FOREIGN KEY (account_user_id) REFERENCES public.account_users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: plan_prices plan_prices_plan_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_prices
    ADD CONSTRAINT plan_prices_plan_slug_fkey FOREIGN KEY (plan_slug) REFERENCES public.plans(slug) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: role_permissions role_permissions_permission_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: role_permissions role_permissions_role_slug_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_role_slug_fkey FOREIGN KEY (role_slug) REFERENCES public.roles(slug) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: subscriptions subscriptions_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: subscriptions subscriptions_last_usage_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_last_usage_transaction_id_fkey FOREIGN KEY (last_usage_transaction_id) REFERENCES public.transactions(id) ON UPDATE CASCADE;


--
-- Name: subscriptions subscriptions_plan_price_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_plan_price_id_fkey FOREIGN KEY (plan_price_id) REFERENCES public.plan_prices(id) ON UPDATE CASCADE;


--
-- Name: transactions transactions_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict acHjbRzMnPeVRcLyt2fBoz8GNyTbJbxDhlznDpNrsfNatHuyyjqbtIfmBPpe42W
